### ISSUE TITLE
v1beta3 API 

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/cluster-api-provider-cloudstack#271]
From few of the features as well as bugs we are tracking, some of them require an API change, which are all sizable enough and non-additive to warrant a new API version. This issue will track all tasks required to introduce the new API version.

```[tasklist]
### Tasks
- [x] Create a new branch `switch-to-v1beta3` which will house all new API until they are stable enough to be merged to `main`
- [x] Basic API skeleton for `v1beta3` version. This includes definition of API, conversions across Hub and Spokes, along with CRDs. PR - https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/272, https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/275
- [x] Changes + Fixes + Features that require API changes planned for `v1beta3`
- [x] Cluster Template changes to point to new API version
- [x] Kubebuilder PROJECT changes to new API version. PR - https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/275
- [x] Add conversions between hub and spoke versions for lossless conversion. PR- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/275
- [x] Merge branch to main
```
